<a href="https://colab.research.google.com/github/priyanka16march/assigenment/blob/master/DAY1_NUMPYBASICS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("we learning numpy")

we learning numpy


In [2]:
import numpy as np

In [3]:
## create 2D array

In [4]:
a1 = np.array([[1,2,3],[5,6,7],[8,5,3],[4,9,6]])

In [5]:
a1

array([[1, 2, 3],
       [5, 6, 7],
       [8, 5, 3],
       [4, 9, 6]])

In [6]:
type(a1)

numpy.ndarray

In [7]:
a1.shape ## no. of rows and cols

(4, 3)

In [8]:
a1.min()  # mini value

1

In [9]:
a1.max()  # max value

9

In [10]:
a1.argmin()  # index of minivalue

0

In [11]:
a1.argmax()  # index of max value

10

In [14]:
a1.ndim # no. of dimenion

2

In [15]:
a1.dtype

dtype('int64')

In [17]:
a1.sum()

59

In [18]:
type(a1)

numpy.ndarray

In [19]:
a1.sum(axis = 0 ) # cols vise sumation

array([18, 22, 19])

In [20]:
a1.sum(axis = 1) # rows vise sumation 

array([ 6, 18, 16, 19])

In [21]:
a1

array([[1, 2, 3],
       [5, 6, 7],
       [8, 5, 3],
       [4, 9, 6]])

In [22]:
### Picking element from array (slicing of array)

In [23]:
a1

array([[1, 2, 3],
       [5, 6, 7],
       [8, 5, 3],
       [4, 9, 6]])

In [24]:
a1[2]  # return 2nd row values

array([8, 5, 3])

In [25]:
a1[:]

array([[1, 2, 3],
       [5, 6, 7],
       [8, 5, 3],
       [4, 9, 6]])

In [26]:
a1[1:4]  # row index from index 1 to index 3

array([[5, 6, 7],
       [8, 5, 3],
       [4, 9, 6]])

In [27]:
a1[:,:]  # complete row n cols]

array([[1, 2, 3],
       [5, 6, 7],
       [8, 5, 3],
       [4, 9, 6]])

In [28]:
a1[:,1]

array([2, 6, 5, 9])

In [30]:
a1[1:4,1:3]

array([[6, 7],
       [5, 3],
       [9, 6]])

In [33]:
## line space function equal distance no.(2,4,6...) fix sample range

In [34]:
a2 = np.linspace(1,100)

In [35]:
a2

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

In [36]:
a2 = np.linspace(1,100,10)

In [37]:
a2

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [38]:
a2 = np.linspace(1,100,retstep = True)

In [39]:
a2

(array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
          9.08163265,  11.10204082,  13.12244898,  15.14285714,
         17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
         25.24489796,  27.26530612,  29.28571429,  31.30612245,
         33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
         41.40816327,  43.42857143,  45.44897959,  47.46938776,
         49.48979592,  51.51020408,  53.53061224,  55.55102041,
         57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
         65.65306122,  67.67346939,  69.69387755,  71.71428571,
         73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
         81.81632653,  83.83673469,  85.85714286,  87.87755102,
         89.89795918,  91.91836735,  93.93877551,  95.95918367,
         97.97959184, 100.        ]), 2.020408163265306)

In [40]:
a2 = np.linspace(1,100,10,retstep = True)

In [41]:
a2

(array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.]), 11.0)

In [42]:
type(a2)

tuple

In [43]:
a2[1]

11.0

In [44]:
a2[0]

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [45]:
a3 = a2[0].astype('int')

In [46]:
a3

array([  1,  12,  23,  34,  45,  56,  67,  78,  89, 100])

In [47]:
## arange function  fix size

In [48]:
a4 = np.arange(1,100,5)

In [49]:

a4

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [50]:
# random numbers 

In [51]:
np.random.randint(100)  ## any random number b/w 0-99

77

In [52]:
np.random.seed(1)
np.random.randint(100)

37

In [53]:
np.random.seed(2)
np.random.randint(100)

40

In [54]:
np.random.seed(200)
np.random.randint(100)

26

In [56]:
# np.random.seed(1)      # variable value if we not use seed
np.random.randint(100)

68

In [57]:

np.random.randint(100,1000)   ## b/w 100-999

910

In [58]:

np.random.randint(100,1000,10)

array([795, 944, 179, 445, 626, 319, 285, 701, 239, 142])

In [59]:

np.random.randint(100,1000,(5,4))

array([[412, 613, 107, 151],
       [301, 243, 741, 338],
       [379, 185, 508, 363],
       [506, 922, 884, 462],
       [903, 604, 344, 259]])

In [77]:
np.random.seed(1)
a = np.random.randint(100,1000,(5,4))




In [82]:
np.random.random(3)

array([0.69232262, 0.87638915, 0.89460666])

In [79]:
np.random.random(10)

array([0.87811744, 0.02738759, 0.67046751, 0.4173048 , 0.55868983,
       0.14038694, 0.19810149, 0.80074457, 0.96826158, 0.31342418])

In [62]:
a

array([[137, 335, 172, 867],
       [815, 745, 947, 244],
       [229, 683, 849, 608],
       [490, 381, 278, 376],
       [354, 457, 568, 352]])

In [66]:
a.min()

137

In [64]:
a.argmin()

0

In [68]:
a[0]

array([137, 335, 172, 867])

In [69]:
b = a.reshape(20,)  ## change the shape as 2d into 1 d

In [70]:
b

array([137, 335, 172, 867, 815, 745, 947, 244, 229, 683, 849, 608, 490,
       381, 278, 376, 354, 457, 568, 352])

In [71]:
b.ndim

1

In [72]:
a.max()

947

In [73]:
a.argmax()

6

In [74]:
b[6]

947

In [75]:
c = a.reshape((10,2))

In [76]:
c

array([[137, 335],
       [172, 867],
       [815, 745],
       [947, 244],
       [229, 683],
       [849, 608],
       [490, 381],
       [278, 376],
       [354, 457],
       [568, 352]])