<a href="https://colab.research.google.com/github/priyanka16march/assigenment/blob/master/DAY1_NUMPYBASICS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("we learning numpy")

we learning numpy


In [2]:
import numpy as np

In [3]:
## create 2D array

In [4]:
a1 = np.array([[1,2,3],[5,6,7],[8,5,3],[4,9,6]])

In [5]:
a1

array([[1, 2, 3],
       [5, 6, 7],
       [8, 5, 3],
       [4, 9, 6]])

In [6]:
type(a1)

numpy.ndarray

In [7]:
a1.shape ## no. of rows and cols

(4, 3)

In [8]:
a1.min()  # mini value

1

In [9]:
a1.max()  # max value

9

In [10]:
a1.argmin()  # index of minivalue

0

In [11]:
a1.argmax()  # index of max value

10

In [14]:
a1.ndim # no. of dimenion

2

In [15]:
a1.dtype

dtype('int64')

In [17]:
a1.sum()

59

In [18]:
type(a1)

numpy.ndarray

In [19]:
a1.sum(axis = 0 ) # cols vise sumation

array([18, 22, 19])

In [20]:
a1.sum(axis = 1) # rows vise sumation 

array([ 6, 18, 16, 19])

In [21]:
a1

array([[1, 2, 3],
       [5, 6, 7],
       [8, 5, 3],
       [4, 9, 6]])